def Home():
    print("**********************************************************")
    print("                      Korean Food")
    print("|    |        |        |        |         |        |     |")
    print("|HOME|        |CARDAPIO|        |SOBRE NÓS|        |LOGIN|")
    print("|    |        |        |        |         |        |     |")
    print("")
    print("EXPLORE SEU #MOMENTO COREANO")
    print("")
    print("        Principais             Porçoes(Acompanhamentos)")
    print("**********************************************************")

def Cardapio():
    print("**********************************************************")
    print("                      Korean Food")
    print("|    |                 |        |                 |     |")
    print("|HOME|                 |CARDAPIO|                 |LOGIN|")
    print("|    |                 |        |                 |     |")
    print("CARDAPIO")
    print("")
    print("*KIMCHI*")
    print("Kimchi é tradicionalmente feito com acelga, gengibre e pimenta\nEsse é um prato que pode ser acompanhado em todas as refeições")
    print("*BIBIMBAP*")
    print("Bibimbap consiste basicamente em arroz branco, vegetais e carne misturados\nPreparados em tigela de pedra vulcânica")
    print("**********************************************************")

def 
    print("**********************************************************")
    print("                      Korean Food")
    print("|    |                 |        |                 |     |")
    print("|HOME|                 |CARDAPIO|                 |LOGIN|")
    print("|    |                 |        |                 |     |")
    print("KIMCHI")
    print("'FOTO'          Prato feito com acelga, gengibre e pimenta")
    print("Escolha abaixo a quantidade que deseja pedir:")
    print("'Caixa de escolha'                                 R$Valor")
    print("                                     Adicionar ao carrinho")
    print("**********************************************************")

print("**********************************************************")
print("                      Korean Food")
print("|    |                 |        |                 |     |")
print("|HOME|                 |CARRINHO|                 |LOGIN|")
print("|    |                 |        |                 |     |")
print("CARRINHO")
print("")
print("Este são os itens que estao em seu carrinho:")
print("Kimchi, 1 unidade  -  R$Valor")
print("")
print("                                          Subtotal:R$Valor")
print("                                             Frete:R$Valor")
print("                                             Total:R$Valor")
print("                                          Finalizar pedido")
print("**********************************************************")

print("**********************************************************")
print("                      Korean Food")
print("Endereço de entrega:                    Forma De Pagamento")
print("CEP:                                                   Pix")
print("Nome completo:                       Cartao Credito/Debito")
print("Numero de Celular:                                  Boleto")
print("                                       Finalizar Pagamento")
print("**********************************************************")

print("**********************************************************")
print("                      Korean Food")
print("|    |")
print("|HOME|")
print("|    |")
print("")
print("ÁREA DE LOGIN")
print("                Email:")
print("                Senha:")
print("")
print("                    'Finalizar Login'")
print("**********************************************************")
def Sobre():
    print("**********************************************************")
    print("                      Korean Food")
    print("|    |                 |         |                 |     |")
    print("|HOME|                 |SOBRE NÓS|                 |LOGIN|")
    print("|    |                 |         |                 |     |")
    print("   Somos um restaurante de Comida Coreana\nServimos diferenciados pratos em nosso estabelecimento\nO melhor estabelecimento do Brasil de Culinaria Coreana")
    print("Para nos contatar utilize o numero de WhatsApp a baixo:\n               1999999-9999")
    print("**********************************************************")